#%RAML 1.0
title: issue-api
version: 1.0.0
mediaType: 
- application/json
protocols: [HTTP,HTTPS]
documentation:
  - title: Documentation for Issue Api
    content: Test Documentation for Issue

traits:
  client-id-required:
    headers:
      client_id:
        type: string
      client_secret:
        type: string
    responses:
      401:
        description: Unauthorized or invalid client application credentials
      500:
        description: Bad response from authorization server, or WSDL SOAP Fault error

types:
  request: !include issueRequest.raml
  response: !include issueResponse.raml
  healthcheck: !include healthcheck.raml

/live:
  get:
    displayName: used to check liveness of the api
    responses:
      200:
        body:
          application/json:
            type: healthcheck
/ready:
  get:
    displayName: used to check readiness of the api
    responses:
      200:
        body:
          application/json:
            type: healthcheck
/health:
  get:
    displayName: combined health (liveness & readiness) check 
    responses:
      200:
        body:
          application/json:
            type: healthcheck
/issue/{quoteId}:
  get:
    is: [client-id-required]
    responses:
      200:
        body:
          application/json:
            type: request
  post:
    is: [client-id-required]
    body:
      application/json:
        type: request
    responses:
      200:
        body:
          application/json:
            type: response
